name: Issue Create 

on:
  issues:
    types: [opened, edited]

jobs:
  issue-welcome:
    runs-on: ubuntu-latest
    steps:
      - name: welcome
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'welcome'
          token: ${{ secrets.GITHUB_TOKEN }}
          body: Hi @${{ github.event.issue.user.login }}, welcome! æ¬¢è¿å‚ä¸åˆ° Datawhale ç¤¾åŒº ğŸ˜ƒ
          labels: 'good first issue'
          issue-emoji: '+1, eyes'
  add-assigness:
    runs-on: ubuntu-latest
    steps:
      - name: Add assigness
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-assignees'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          assignees: 'SuperSupeng'
          random-to: 1
